export const mockInstitutions: Institution[] = [
    {
        id: 79266584,
        name: 'Orfanato Brilho Feliz',
        email: 'orfanatobrilhofeliz@gmail.com',
        contactNumber: 91987321961,
        description: 'Instituição de acolhimento dedicada a oferecer um lar seguro e afetuoso para crianças e adolescentes.',
    },
    {
        id: 75448667,
        name: 'Lar Esperança Viva',
        email: 'laresperancaviva@gmail.com',
        contactNumber: 21987654321,
        description: 'Acolhe famílias em situação de vulnerabilidade, oferecendo moradia temporária e apoio social.',
    },
    {
        id: 59911584,
        name: 'Centro Cultural Sementes',
        email: 'centrosementes@gmail.com',
        contactNumber: 11988887777,
        description: 'Espaço que promove oficinas culturais e artísticas para jovens e adultos da comunidade.',
    },
    {
        id: 75573816,
        name: 'Abrigo Luz do Amanhã',
        email: 'luzdoamanha@gmail.com',
        contactNumber: 31999995555,
        description: 'Abrigo especializado em apoio a pessoas idosas em situação de abandono.',
    },
    {
        id: 45880994,
        name: 'Associação Amigos dos Animais',
        email: 'amigosanimais@gmail.com',
        contactNumber: 71922223333,
        description: 'Organização dedicada ao resgate, tratamento e adoção de animais em risco.',
    },
    {
        id: 33422324,
        name: 'Instituto Verde Vida',
        email: 'institutoverdevida@gmail.com',
        contactNumber: 81955557777,
        description: 'Instituto voltado para a preservação ambiental e conscientização ecológica.',
    },
    {
        id: 76868066,
        name: 'Projeto Jovem Futuro',
        email: 'jovemfuturo@gmail.com',
        contactNumber: 51977776666,
        description: 'Oferece cursos de capacitação profissional para jovens de baixa renda.',
    },
    {
        id: 16573250,
        name: 'Casa das Artes',
        email: 'casadasartes@gmail.com',
        contactNumber: 61911112222,
        description: 'Espaço cultural que promove exposições, peças teatrais e shows musicais.',
    },
    {
        id: 36684218,
        name: 'Hospital Comunitário Bem Viver',
        email: 'hospitalbemviver@gmail.com',
        contactNumber: 71966665555,
        description: 'Hospital que oferece atendimento gratuito e humanizado à comunidade local.',
    },
    {
        id: 24466973,
        name: 'Centro Esportivo Vitória',
        email: 'centrovitoria@gmail.com',
        contactNumber: 31933334444,
        description: 'Centro esportivo com foco em inclusão social por meio do esporte.',
    },
];